<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
<form action="index.php" method="POST">
    <?php if(isset($error)): ?>
    <div class="alert alert-success">
        <?= $error ?></div>
    <?php endif; ?>

    <?php if(isset($good)): ?>
    <div class="alert alert-success">
        <?= $good ?></div>
    <?php endif; ?>
  <div class="form-group">
    <label>name</label>
    <input type="text" name="name" class="form-control">
  </div>
  <div class="form-group">
    <label>mcube</label>
    <input type="number" step="0.01" name="mcube" class="form-control">
  </div>
  <div class="form-group">
    <label>Type de mobilier</label>
    <select name="type" class="form-control">
      <option value="3">Cuisine</option>
      <option value="4">Bureau</option>
      <option value="5">Salle de Bain</option>
      <option value="6">Autres</option>
    </select>
</div>
<div class="form-group">
    <input type="submit" class="btn btn-outline-success" value="Enregistrer">
</div>
</form>
</body>
</html>