<div class="col-md-12">

    <form method="post" id="addForm" class="wpcf7-form" novalidate>

        <div class="slide-title">
            <h2>Adresses du déménagement</h2>
        </div>
        <div id="depBox">

            <h5 class="heading font-size-30 mb-1">Départ</h5>
            <span class="form-group">
                <div id="locationField">
                    <input id="autocomplete" placeholder="Adresse *" onFocus="geolocate()" type="text" tabindex="1"
                        name="Adresse départ" value="" class="wpcf7-form-control" required />
                </div>
            </span>
            <div class="row">
                <span class="form-group col-md-6">
                    <input type="text" tabindex="2" id="postal_code" name="Code-postal départ" value="" class="wpcf7-form-control"
                        placeholder="Code postal *" required>
                </span>
                <span class="form-group col-md-6">
                    <input type="text" tabindex="3" id="locality" name="Ville départ" value="" class="wpcf7-form-control"
                        placeholder="Ville *" required>
                </span>
            </div>
            <div class="row">
                <span class="form-group col-md-6">
                    <select name="Type_départ" id="typeDep" class="wpcf7-form-control" required>
                        <option selected disabled>Type... *</option>
                        <option value="Appartement">Appartement</option>
                        <option value="Maison">Maison</option>
                        <option value="Garde-meuble">Garde-meuble</option>
                    </select>
                </span>

                <span class="form-group col-md-6">
                    <div class="input-group">
                        <div class="input-group-append">
                            <span class="input-group-text mb-0">m³</span>
                        </div>
                        <input type="number" tabindex="3" id="surfaceDep" name="Surface départ" value=""
                            class="wpcf7-form-control form-control" placeholder="Surface m³" required>
                    </div>
                </span>
            </div>

            <div data-condition="input.Type_départ == 'Appartement'" class="col-12 p-0" style="display: none;">
                <div class="row">
                    <div class="options options-buttons col-6">
                        <select name="Etage départ" id="etageAppDep" class="adresse-etage" required>
                            <option disabled selected value="" placeholder="">Etage</option>
                            <option value="RDC">RDC</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                            <option value="13">13</option>
                            <option value="14">14</option>
                            <option value="15">15</option>
                            <option value="16">16</option>
                            <option value="17">17</option>
                            <option value="18">18</option>
                            <option value="19">19</option>
                            <option value="20">20</option>
                        </select>
                    </div>

                    <div class="options options-buttons col-6">
                        <select name="ascenseur_départ" id="ascAppDep" required>
                            <option disabled selected value="" placeholder="">Ascenseur *</option>
                            <option value="oui">Oui</option>
                            <option value="non">Non</option>
                        </select>

                        <div data-condition="input.ascenseur_départ == 'oui'" style="display: none;">
                            <select name="Taille ascenseur départ" id="sizeAscAppDep" required>
                                <option disabled selected value="" placeholder="">Séléctionnez la place
                                    maximale</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="6+">6+</option>
                            </select>
                        </div>
                    </div>

                </div>

                <div class="row">

                    <div class="options options-buttons col-6">
                        <select name="Cave départ" id="caveAppDep" required>
                            <option disabled selected value="" placeholder="">Cave *</option>
                            <option value="oui">Oui</option>
                            <option value="non">Non</option>
                        </select>
                    </div>
                    <div class="options options-buttons col-6">
                        <select name="Monte-charge départ" id="monteAppDep" required>
                            <option disabled selected value="" placeholder="">Monte-charge *</option>
                            <option value="oui">Oui</option>
                            <option value="non">Non</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="options options-buttons col-12">
                        <h3 class="mb-0 mt-2">Distance logement / rue</h3>
                        <input id="distAppDep" name="Distance logement/rue départ" class="adresse-distance" required />
                    </div>
                </div>
            </div>

            <div data-condition="input.Type_départ == 'Maison'" class="col-12 p-0" style="display: none;">
                <div class="row">

                    <div class="options options-buttons col-6">
                        <select name="Etage départ" id="etageHomeDep" class="adresse-etage" required>
                            <option disabled selected value="" placeholder="">Etage</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                    </div>

                    <div class="options options-buttons col-6">
                        <select name="Monte-charge départ" id="monteHomeDep" required>
                            <option disabled selected value="" placeholder="">Monte-charge *</option>
                            <option value="oui">Oui</option>
                            <option value="non">Non</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <select name="Garde-meuble départ" id="gardeHomeDep" required>
                            <option disabled selected value="" placeholder="">Garde-meuble *</option>
                            <option value="oui">Oui</option>
                            <option value="non">Non</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="options options-buttons col-12">
                            <h3 class="mb-0 mt-2">Distance logement/rue</h3>
                            <input id="distHomeDep" name="Distance logement/rue départ" class="adresse-distance" required />
                        </div>
                    </div>
                </div>

            </div>


            <div data-condition="input.typeDep == 'oui' &amp;&amp;  input.group6 == 'oui'" style="display: none;">
                <p>This message appears after all conditions have been marked as "yes".</p>
            </div>

            <span class="form-group">
                <textarea name="Commentaire départ" id="commentDep" tabindex="5" row="5" class="wpcf7-form-control wpcf7-textarea"
                    placeholder="Complément: Batîment, code, porte, autre ..."></textarea>
            </span>



        </div>






        <div id="arrBox">

            <h5 class="heading font-size-30 mb-1 mt-3">Arrivée</h5>
            <span class="form-group">
                <div id="locationField">
                    <input id="autocomplete2" placeholder="Adresse *" onFocus="geolocate()" type="text" tabindex="1"
                        name="Adresse arrivée" value="" class="wpcf7-form-control" required />
                </div>
            </span>
            <div class="row">
                <span class="form-group col-md-6">
                    <input type="text" tabindex="2" id="postal_code_2" name="Code postal arrivée" value="" class="wpcf7-form-control"
                        placeholder="Code postal *" required>
                </span>
                <span class="form-group col-md-6">
                    <input type="text" tabindex="3" id="locality_2" name="Ville arrivée" value="" class="wpcf7-form-control"
                        placeholder="Ville *" required>
                </span>
            </div>
            <div class="row">
                <span class="form-group col-md-6">
                    <select name="Type_arrivée" id="typeArr" class="wpcf7-form-control" required>
                        <option selected disabled>Type... *</option>
                        <option value="Appartement">Appartement</option>
                        <option value="Maison">Maison</option>
                        <option value="Garde-meuble">Garde-meuble</option>
                    </select>
                </span>

                <span class="form-group col-md-6">
                    <div class="input-group">
                        <div class="input-group-append">
                            <span class="input-group-text mb-0">m³</span>
                        </div>
                        <input type="number" tabindex="3" id="surfaceArr" name="Surface arrivée" value=""
                            class="wpcf7-form-control form-control" placeholder="Surface m³" required>
                    </div>
                </span>
            </div>
            <div data-condition="input.Type_arrivée == 'Appartement'" class="col-12 p-0" style="display: none;">
                <div class="row">
                    <div class="options options-buttons col-6 form-group">
                        <select name="Etage(s) arrivée" id="etageAppArr" class="adresse-etage" required>
                            <option disabled selected value="" placeholder="">Etage</option>
                            <option value="RDC">RDC</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                            <option value="13">13</option>
                            <option value="14">14</option>
                            <option value="15">15</option>
                            <option value="16">16</option>
                            <option value="17">17</option>
                            <option value="18">18</option>
                            <option value="19">19</option>
                            <option value="20">20</option>
                        </select>
                    </div>

                    <div class="options options-buttons col-6 form-group">
                        <select name="Ascenseur_arrivée" id="ascAppArr" required>
                            <option disabled selected value="" placeholder="">Ascenseur *</option>
                            <option value="oui">Oui</option>
                            <option value="non">Non</option>
                        </select>

                        <div data-condition="input.Ascenseur_arrivée == 'oui'" style="display: none;">
                            <select name="Taille ascenseur arrivée" id="sizeAscAppArr" required>
                                <option disabled selected value="" placeholder="">Séléctionnez la place
                                    maximale</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="6+">6+</option>
                            </select>
                        </div>
                    </div>

                </div>

                <div class="row">

                    <div class="options options-buttons col-6 form-group">
                        <select name="Cave arrivée" id="caveAppArr" required>
                            <option disabled selected value="" placeholder="">Cave *</option>
                            <option value="oui">Oui</option>
                            <option value="non">Non</option>
                        </select>
                    </div>
                    <div class="options options-buttons col-6 form-group">
                        <select name="Monte-charge arrivée" id="monteAppArr" required>
                            <option disabled selected value="" placeholder="">Monte-charge *</option>
                            <option value="oui">Oui</option>
                            <option value="non">Non</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="options options-buttons col-12">
                        <h3 class="mb-0 mt-2">Distance logement / rue</h3>
                        <input id="distAppArr" name="Distance logement/rue arrivée" class="adresse-distance" required />
                    </div>
                </div>
            </div>

            <div data-condition="input.Type_arrivée == 'Maison'" class="col-12 p-0" style="display: none;">
                <div class="row">

                    <div class="options options-buttons col-6">
                        <select name="Etage arrivée" id="etageHomeArr" class="adresse-etage" required>
                            <option disabled selected value="" placeholder="">Etage</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                    </div>

                    <div class="options options-buttons col-6">
                        <select name="Monte-charge arrivée" id="monteHomeArr" required>
                            <option disabled selected value="" placeholder="">Monte-charge *</option>
                            <option value="oui">Oui</option>
                            <option value="non">Non</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <select name="Garde-meuble arrivée" id="gardeHomeArr" required>
                            <option disabled selected value="" placeholder="">Garde-meuble *</option>
                            <option value="oui">Oui</option>
                            <option value="non">Non</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="options options-buttons col-12">
                            <h3 class="mb-0 mt-2">Distance logement/rue</h3>
                            <input id="distHomeArr" name="Distance logement/rue arrivée" class="adresse-distance" required />
                        </div>
                    </div>
                </div>

            </div>

            <div data-condition="input.typeArr == 'oui' &amp;&amp;  input.group6 == 'oui'" style="display: none;">
                <p>This message appears after all conditions have been marked as "yes".</p>
            </div>


            <span class="form-group">
                <textarea name="Commentaire arrivée" id="commentArr" tabindex="5" row="5" class="wpcf7-form-control wpcf7-textarea"
                    placeholder="Complément: Batîment, code, porte, autre ..."></textarea>
            </span>
        </div>


    </form>
</div>

<script>
            var OKButton;
            setTimeout(() => {
            OKButton = $('#adressesForm .slideform-btn-next')[0];
            OKButton.addEventListener('click', () => {
                let inputs = $("#addForm").serializeArray();
                let inputList = []
                /* Cart.addItem({
                    id:"adressesDem"
                }) */
                inputs.forEach(input =>{
                    console.log(input);
                    if(input.name.split(" ")[0] == "Etage"){
                        if(input.name.split(" ")[1] == "départ"){
                            if(input.value > 3){
                                Cart.addItem({
                                    id: "etageDep",
                                    quantity: -Infinity,
                                })
                                Cart.addItem({
                                    id: "etageDep",
                                    quantity: input.value - 3,
                                    label: input.name,
                                    price: 30
                                })
                            }
                        }
                        if(input.name.split(" ")[1] == "arrivée"){
                            if(input.value > 3){
                                Cart.addItem({
                                    id: "etageArr",
                                    quantity: -Infinity,
                                })
                                Cart.addItem({
                                    id: "etageArr",
                                    quantity: input.value - 3,
                                    label: input.name,
                                    price: 30
                                })
                            }
                        }
                    }
                        if(input.name == "Type_arrivée"){

                            if(input.value == "Garde-meuble"){
                                Cart.addItem({
                                    id: "etageDep",
                                    quantity: -Infinity,
                                })
                                Cart.addItem({
                                    id: "distPortageDep",
                                    quantity: -Infinity,
                                })
                        }
                        }

                        if(input.name == "Type_départ"){
                            if(input.value == "Garde-meuble"){
                                Cart.addItem({
                                    id: "etageArr",
                                    quantity: -Infinity,
                                })
                                Cart.addItem({
                                    id: "distPortageArr",
                                    quantity: -Infinity,
                                })
                        }
                    }


                    if(input.name.split(" ")[0] == "Distance"){

                        if(input.name.split(" ")[2] == "arrivée"){
                            if(input.value > 10){
                                Cart.addItem({
                                    id: "distPortageArr",
                                    quantity: -Infinity,
                                })
                                Cart.addItem({
                                    id: "distPortageArr",
                                    quantity: input.value - 10,
                                    label: input.name,
                                    price: 1
                                })
                            }
                        }

                        if(input.name.split(" ")[2] == "départ"){
                            if(input.value > 10){
                                Cart.addItem({
                                    id: "distPortageDep",
                                    quantity: -Infinity,
                                })
                                Cart.addItem({
                                    id: "distPortageDep",
                                    quantity: input.value - 10,
                                    label: input.name,
                                    price: 1
                                })
                            }
                        }
                    }
                   inputList.push(input)
                })
                console.log(inputList)
                localStorage.setItem('adressesDem', JSON.stringify(inputList));
            }); },2000);
            /* let inputs = document.getElementById('addForm').getElementsByTagName('input');
            let selects = document.getElementById('addForm').getElementsByTagName('select');
            let textAreas = document.getElementById('addForm').getElementsByTagName('textarea');

            let etages = document.getElementsByClassName('adresses-etage');
            let distances = document.getElementsByClassName('adresses-distance');

            let departure = []
            let arrival = []



            for (var i = 0; i < inputs.length; i++) {
                input = inputs[i];
                input.addEventListener('change', e => {
                    Cart.addItem({
                        id: "adresses",
                        quantity:-1,
                    })
                    Cart.addItem({
                        id: "adresses",

                    })
                })
            }

            for (var i = 0; i < selects.length; i++) {
                select = selects[i];
                select.addEventListener('change', e => {
                    Cart.addItem({
                        id: e.target.id,
                        quantity:-1,
                    })
                    Cart.addItem({
                        id: e.target.id,
                        label: e.target.value,
                    })
                })

            }

            for (var i = 0; i < textAreas.length; i++) {
                textArea = textAreas[i];
                textArea.addEventListener('change', e => {
                    Cart.addItem({
                        id: e.target.id,
                        quantity:-1,
                    })
                    Cart.addItem({
                        id: e.target.id,
                        label: e.target.value,
                    })
                })
            } */


</script>
