<div class="col-md-12">
    <div class="col-md-12 col-xs-12">
        <div class="">
            <h2 class="slide-title">En cas de problème annulez sans frais</h2>
            <h3 class="font-size-20">Annulez jusqu'à 72h avant votre déménagement sans frais, sans
                conditions.</h3>
        </div>
    </div>
    <div class="">
        <div class="col-md-12 mt-5">
            <img src="assets/imgs/annulation.png" alt="" class="img-responsive hidden-xs">
            <!-- <img src="assets/imgs/annulation-responsive.jpg" alt="" class="img-responsive visible-xs"> -->
        </div>
        <br clear="all">
        <div class="row">
            <div class="col-md-6 hidden-xs text-left">
                <p>* Sans l'option : à condition d’en faire la demande dans les 7 jours qui suivent
                    la
                    commande.</p>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="options options-buttons">
            <h4>Choisir l'option</h4>
            <label for=""><input type="radio" name="radioAnnulation" id="radioAnnulationY" data-price="60" data-label="Assurance annulation"><span id="radioAnnulationYLabel">Oui</span></label>
            <label for=""><input type="radio" name="radioAnnulation" id="radioAnnulationN" data-price="0"><span id="radioAnnulationNLabel">Non</span></label>
        </div>
    </div>
</div>
<script>
  var OKButton;
            setTimeout(() => {
            OKButton = $('#annulationForm .slideform-btn-next');
            OKButton.on('click', e => {
                let qty = Cart.getFullItem('annulation').quantity;
                let id = Cart.getFullItem('annulation').id;
                let uid = localStorage.getItem('uid');
                $.ajax({
                  method: "POST",
                  url: "includes/contact/ajax-devis.php",
                  data: { qty: qty, id: id, uid: uid}
                })

            }); },2000);
  </script>
