<div class="col-md-12 ">
    <h2 class="tunnel">Durée de la prestation</h2>
    <h4 class="">A partir du moment où les déménageurs arrivent chez vous.</h4>
    <div class="row mb-5">


        <div class="col-md-6" id="">
            <div class="box_transport border">
                <div class="box_duree" id="boxDuree4h">
                    <div class="select-icon col-md-1 col-sm-2">

                    <div class="radio radio-success radio-single">
                        <input type="radio" id="radio4h" name="duree-presta" value="option2" data-label="Prestation 4h" data-price="100" aria-label="Single checkbox Two">
                        <label></label>
                    </div>

                    </div>
                    <div class="picture ">
                        <img src="" class="img-responsive" alt="">
                    </div>
                    <h4>4 heures</h4>
                    <p>Convient aux studios et petits appartements.</p>
                    <div class="mx-auto wpcf7-form">
                        <select class="wpcf7-form-control demi_journee_news demi_journee_val" name="demi_journee_news">
                            <option disabled selected value="">Créneau d'intervention des déménageurs</option>
                            <option value="Déménagement le matin">Matin</option>
                            <option value="Déménagement l'après-midi">Aprés-Midi</option>
                        </select>
                    </div>
                    <br clear="all">
                </div>
            </div>
        </div>


        <div class="col-md-6" id="">
            <div class="box-transport border">
                <div class="box_duree" id="boxDuree7h">
                    <div class="select-icon col-md-1 col-sm-2">
                        <div class="radio radio-success radio-single">
                            <input type="radio" name="duree-presta" id="radio7h" data-label="Prestation 7h" data-price="100" value="" aria-label="">
                            <label></label>
                        </div>
                    </div>
                    <div class="picture ">
                        <img src="" class="img-responsive" alt="">
                    </div>
                    <h4>7 heures</h4>
                    <p>La formule la plus populaire pour les 2 pièces et les appartements jusqu’à
                        50m2.</p>
                    <br clear="all">
                </div>
            </div>
        </div>

    </div>
</div>

<div class="col-md-12 row">
    <div class="col-md-8 mb40">
        <h3><b>Heure d'arrivée des déménageurs : </b></h3>
        <ul class="check-circle">
            <li>Formules 4 heures : Matin : entre 8 et 9 heure // Après-midi : entre 12 et 14
                heure</li>
            <li>Formules 7 heures : entre 8 et 9 heure</li>
        </ul>
        <h3><b>Et si ce n’est pas suffisant ?</b></h3>
        <p class="">Vous pouvez prendre une à deux heures supplémentaire(s) le jour
            du déménagement pour finaliser votre prestation au tarif de 70€/heure/déménageur.</p>
    </div>
    <div class="col-md-4 cas-pratique">
        <h4 class=""><i class="fa fa-lightbulb"></i> CAS PRATIQUE</h4>
        <p class=" ">Si votre déménageur souhaite prendre une pause, la
            durée de votre prestation est automatiquement prolongée de cette même durée.</p>
    </div>
</div>
