<div class="slide-title">
    <h2>Garanties</h2>
</div>
<div class="col-xs-12">
    <div class="row col-md-12 mx-0 px-0">
        <div id="default-assurance" class="assurance-card border col-md-5 p-5 font-size-15 text-dark text-left">
            <div class="radio radio-success radio-single">
                <input type="radio" id="radioGarantieDef" data-id="radioGarantieDef" data-price="100" data-label="Garantie par défaut" value="option2.1" name="radioSingle1" checked="" aria-label="Single radio Two">
                <label></label>
            </div>
            <div class="title-assurance font-size-20 text-center">
                Garantie par défaut
            </div>
            <div class="row col-md-12 mx-auto">
                <div class="col-md-5 col-xs-6">
                    Couvre au total
                </div>
                <div class="col-md-7 col-xs-6">
                    Jusqu’à
                </div>
            </div>
            <div class="row col-md-12 mx-auto information-assurance text-muted">
                <div class="col-md-5 col-xs-5 valeur-assurance">
                    300€
                </div>
                <div class="col-md-7 col-xs-7 valeur-assurance ml-0">
                    70€ <span>/ objet</span>
                </div>
            </div>
            <p class="">Attention, cette garantie minimale pourrait ne pas
                suffire.</p>
        </div>

        <div class="col-md-2">

        </div>

        <div id="basic-assurance" class="assurance-card border col-md-5 p-5 font-size-15 text-dark text-left">
            <div class="radio radio-success radio-single">
                <input type="radio" id="radioGarantieBas" data-id="radioGarantieBas" data-price="200" data-label="Garantie de base" value="option1.1" name="radioSingle1" aria-label="Single radio One">
                <label></label>
            </div>
            <div class="title-assurance font-size-20 text-center">
                GARANTIE DE BASE
            </div>
            <div class="row col-md-12 mx-auto information-assurance-title">
                <div class="col-md-5 col-xs-6">
                    Couvre au total
                </div>
                <div class="col-md-7 col-xs-6">
                    Jusqu’à
                </div>
            </div>
            <div class="row col-md-12 mx-auto information-assurance  purple">
                <div class="col-md-5 col-xs-5 valeur-assurance">
                    25K
                </div>
                <div class="col-md-7 col-xs-7 valeur-assurance pr-0">
                    1500€ <span>/ objet</span>
                </div>
                <p class="">Une franchise client de 250€ est appliquée.</p>
            </div>
        </div>
    </div>

</div>

<script>
  var OKButton;
            setTimeout(() => {
            OKButton = $('#garantiesForm .slideform-btn-next');
            OKButton.on('click', e => {
                let label = Cart.getFullItem('garantie').label;
                let id = Cart.getFullItem('garantie').id;
                let uid = localStorage.getItem('uid');
              if(!Cart.getItem("garantie")){
                $("#garantieFailModal").modal("show");
              }else{
                $.ajax({
                  method: "POST",
                  url: "includes/contact/ajax-devis.php",
                  data: { label: label, id: id, uid: uid}
                })

              }
            }); },2000);
  </script>
