<!-- Modal -->
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="sendMailModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="sendMailModalLabel">Recevoir Son Devis Par Email</h5>
                <button type="button" class="cbr-button out-line-2px button-has-bg-2 close modal-close"
                    data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <form action="" method="" class="contact-form wpcf7-form"
                novalidate="novalidate">
                <div class="modal-body">
                    <span class="form-control-wrap your-name">
                        <input type="email" tabindex="1" id="user_email" name="email" value="" class="wpcf7-form-control"
                            placeholder="Email *" required="">
                    </span>
                </div>
                <div class="modal-footer">
                    <p id="sendEmailSuccess" class="text-success col-md-6 mr-5 mb-0">Le devis à bien été envoyé</p>
                    <p id="sendEmailDanger" class="text-danger col-md-6 mr-5 mb-0">Il y a eu une erreur veuillez réessayer</p>
                    <div class="cbr-animation-box animated mt-4 animated" style="visibility: visible;">
                        <a href="javascript:{}" id="sendEmail" class="cbr-button px-2 btn-sm out-line-2px button-has-bg-3"><span
                                class="text-uppercase">Envoyer</span></a>
                    </div>
                    <div class="cbr-animation-box animated mt-4 animated" style="visibility: visible;">
                        <a href="#" class="cbr-button px-2 btn-sm out-line-2px button-has-bg-2" data-dismiss="modal"><span
                                class="text-uppercase">Fermer</span></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="calcObjectFailModal" tabindex="-1" role="dialog" aria-labelledby="calcObjectFailModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="calcObjectFailModalLabel"></h5>
                <button type="button" class="cbr-button out-line-2px button-has-bg-2 close modal-close"
                    data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <form action="" method="" class="contact-form wpcf7-form"
                novalidate="novalidate">
                <div class="modal-body">
                    <b class="font-size-18 text-uppercase">veuillez choisir au minimum un objet</b>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="dateFailModal" tabindex="-1" role="dialog" aria-labelledby="dateFailModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="dateFailModalLabel"></h5>
                <button type="button" class="cbr-button out-line-2px button-has-bg-2 close modal-close"
                    data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <form action="" method="" class="contact-form wpcf7-form"
                novalidate="novalidate">
                <div class="modal-body">
                    <b class="font-size-18 text-uppercase">veuillez séléctionner une date</b>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="garantiesFailModal" tabindex="-1" role="dialog" aria-labelledby="garantiesFailModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="garantiesFailModalLabel"></h5>
                <button type="button" class="cbr-button out-line-2px button-has-bg-2 close modal-close"
                    data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <form action="" method="" class="contact-form wpcf7-form"
                novalidate="novalidate">
                <div class="modal-body">
                    <b class="font-size-18 text-uppercase">veuillez choisir une option de garantie</b>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="nbDemenFailModal" tabindex="-1" role="dialog" aria-labelledby="nbDemenFailModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="nbDemenFailModalLabel"></h5>
                <button type="button" class="cbr-button out-line-2px button-has-bg-2 close modal-close"
                    data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <form action="" method="" class="contact-form wpcf7-form"
                novalidate="novalidate">
                <div class="modal-body">
                    <b class="font-size-18 text-uppercase">veuillez choisir le nombre de déménageur(s)</b>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="tailleCamionFailModal" tabindex="-1" role="dialog" aria-labelledby="tailleCamionFailModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="tailleCamionFailModalLabel"></h5>
                <button type="button" class="cbr-button out-line-2px button-has-bg-2 close modal-close"
                    data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <form action="" method="" class="contact-form wpcf7-form"
                novalidate="novalidate">
                <div class="modal-body">
                    <b class="font-size-18 text-uppercase">veuillez choisir une option pour le camion</b>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="dureePrestaFailModal" tabindex="-1" role="dialog" aria-labelledby="dureePrestaFailModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="dureePrestaFailModalLabel"></h5>
                <button type="button" class="cbr-button out-line-2px button-has-bg-2 close modal-close"
                    data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <form action="" method="" class="contact-form wpcf7-form"
                novalidate="novalidate">
                <div class="modal-body">
                    <b class="font-size-18 text-uppercase">veuillez choisir une option d'heure</b>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
$(document).ready(function(){
$('#sendEmailSuccess').hide();
$('#sendEmailDanger').hide();
$('#sendEmail').click(function(){
   $.ajax({
       type: 'POST',
       url: 'includes/contact/contact-checkout.php',
       data: { email: $('#user_email').val(),content: $('#resume_container').html()},
   }).done(function() {
    $('#sendEmailSuccess')
    .show(1000)
    .delay(1500)
    .hide(1000)
  }).fail(function(){
    $('#sendEmailDanger')
    .show(1000)
    .delay(1500)
    .hide(1000)
  })
});

});
</script>
