<div class="col-md-12">
    <h2 class=" tunnel">Sélectionnez le nombre de déménageurs</h2>
    <h4 class="">Tous les déménageurs Atradem sont <span class="orange">des
            professionnels du déménagement.</span></h4>
    <div class="alert alert-danger fade in" style="display:none;">
        <i data-dismiss="alert" class="icon-remove close"></i>
        <strong></strong>
    </div>

    <div class="col-md-12 d-flex mb-5">
        <div class="col-md-2 col-xs-2 hover-bloc-transport no-padding" id="hover-bloc-transport-1">
            <div class="div-bloc-transport bloc-transport-1 no-margin no-padding no-border no-box-shadow" id="bloc-transport-1">
                <div class="picture ">
                    <img src="" class="img-responsive choix-demenageur img-center"
                        alt="" id="1">
                </div>
                <h2 class="text-center text-orange">1</h2>
                <input type="radio" name="nb-demenageurs" class="radio-nb-demen" id="radio-nb-demen-1" data-price="19.90" data-id="radio-nb-demen" data-label="1 Déménageur"
                    value="1">
            </div>
        </div>
        <div class="col-md-2 col-xs-2 no-padding hover-bloc-transport" id="hover-bloc-transport-2">
            <div class="div-bloc-transport bloc-transport-2 no-margin no-padding no-border no-box-shadow" id="bloc-transport-2">
                <div class="picture ">
                    <img src="" class="img-responsive choix-demenageur img-center"
                        alt="" id="2">
                </div>
                <h2 class="text-center text-orange">2</h2>
                <input type="radio" name="nb-demenageurs" class="radio-nb-demen" id="radio-nb-demen-2" data-price="19.90" data-id="radio-nb-demen" data-label="2 Déménageurs"
                    value="2">
            </div>
        </div>
        <div class="col-md-2 col-xs-2 no-padding hover-bloc-transport" id="hover-bloc-transport-3">
            <div class="div-bloc-transport bloc-transport-3 no-margin no-padding no-border no-box-shadow" id="bloc-transport-3">
                <div class="picture ">
                    <img src="" class="img-responsive choix-demenageur img-center"
                        alt="" id="3">
                </div>
                <h2 class="text-center text-orange">3</h2>
                <input type="radio" name="nb-demenageurs" class="radio-nb-demen" id="radio-nb-demen-2" data-price="19.90" data-id="radio-nb-demen" data-label="2 Déménageurs"
                    value="3">
            </div>
        </div>
        <div class="col-md-2 col-xs-2 hover-bloc-transport-noselect no-padding" id="hover-bloc-transport-4">
            <div class="div-bloc-transport bloc-transport-4 no-margin no-padding no-border no-box-shadow" id="bloc-transport-4">
                <div class="picture ">
                    <img src="" class="img-responsive choix-demenageur img-center"
                        alt="" id="4">
                </div>
                <h2 class="text-center text-orange">4</h2>
                <input type="radio" name="nb-demenageurs" class="radio-nb-demen" id="radio-nb-demen-3" data-price="19.90" data-id="radio-nb-demen" data-label="3 Déménageurs"
                    value="3">
            </div>
        </div>
        <div class="col-md-2 col-xs-2 hover-bloc-transport-noselect no-padding" id="hover-bloc-transport-5">
            <div class="div-bloc-transport bloc-transport-5 no-margin no-padding no-border no-box-shadow" id="bloc-transport-5">
                <div class="picture ">
                    <img src="" class="img-responsive choix-demenageur img-center"
                        alt="" id="5">
                </div>
                <h2 class="text-center text-orange">5</h2>
                <input type="radio" name="nb-demenageurs" class="radio-nb-demen" id="radio-nb-demen-5" data-price="19.90" data-id="radio-nb-demen" data-label="5 Déménageurs"
                    value="5">
            </div>
        </div>
        <div class="col-md-2 col-xs-2 hover-bloc-transport-noselect no-padding" id="hover-bloc-transport-6">
            <div class="div-bloc-transport bloc-transport-6 no-margin no-padding no-border no-box-shadow" id="bloc-transport-6">
                <div class="picture ">
                    <img src="" class="img-responsive choix-demenageur img-center"
                        alt="" id="6">
                </div>
                <h2 class="text-center text-orange">6</h2>
                <input type="radio" name="nb-demenageurs" class="radio-nb-demen" id="radio-nb-demen-6" data-price="69.90" data-id="radio-nb-demen" data-label="6 Déménageur"
                    value="6">
            </div>
        </div>
    </div>
    <div class="row col-md-12">
        <div class="col-md-8 col-xs-12">
            <h3><b>Comment choisir ?</b></h3>
            <p class="font16">Un doute sur la personnalisation de votre formule ? Voici quelques
                critères à prendre en considération</p>
            <ul class="">
                <li>Combien de personnes pourront prêter main forte aux déménageurs ?</li>
                <li>Quelles sont les difficultés (accès, étage, présence d'un ascenseur ...) ?</li>
                <li>Où en serez-vous le jour du déménagement (avancement de l'emballage,
                    démontage/remontage à prévoir...) ?</li>
                <li>A quelles tâches seront affectés les déménageurs (chargement, emballage,
                    démontage ...) ?</li>
            </ul>
        </div>
        <div class="col-md-4 col-xs-12 cas-pratique">
            <h4 class="text-orange"><i class="fa fa-lightbulb"></i> CAS PRATIQUE</h4>
            <p class="mb-0">En moyenne, il faut compter deux déménageurs sur 1 journée pour
                charger, décharger et remettre en place le contenu d’un camion de 22m3.</p>
        </div>
        <br clear="all">
    </div>
</div>
