<div class="col-xs-12">
    <h2 class="slide-title">
        Choisir mes options
    </h2>
    <h4>Vos options adaptées à vos besoins</h4>
</div>

<div class="col-md-12">

    <div class="row border opt" id="optMonteMeuble">
        <div class="select-icon col-md-1 col-sm-2">
            <div class="checkbox checkbox-success checkbox-single">
                <input type="checkbox" id="checkboxGarantieBas" value="Basique"  aria-label="Single checkbox Two">
                <label></label>
            </div>
        </div>
        <div class="picture col-md-2 col-sm-10">
            <img src="" alt="Monte meubles"
                class="img-responsive">
        </div>
        <div class="col-md-7 col-sm-12">
            <div class="col-md-12 no-padding">
                <h2>Monte meubles</h2>
            </div>
            <div class="col-md-12 no-padding">
                <div class="col-md-9 mx-auto">
                    <p class="w-100">Avec le Monte meubles, finie la corvée de repassage ou les dépenses de
                        pressing après le
                        déménagement.
                        Mise à disposition d’une penderie en plastique robuste et facile à transporter pendant la
                        prestation.
                        Dimensions (intérieur) : 50 x 50 x 100 cm
                        Placez y jusqu’à 20 chemises, 10 costumes complets ou encore 10 manteaux
                        (Matériel récupéré à l'issue de la prestation)</p>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <form action="#" method="post" class="cart_1" id="add_service">
                <input type="hidden" id="id_send" value="1">
                <div class="form-group">
                    <select title="1" id="1" name="option_select_1" class="option_select_details form-control">
                        <option value="0">Aucun</option>
                        <option value="300:Monte meubles avec technicien demi journée (4h max - 1 adresse max)">
                            Demi-journée</option>
                        <option value="500:Monte meubles avec technicien journée entière (7h max - 2 adresses max)">
                            Journee</option>
                    </select>
                </div>
            </form>

            <p class="prix-options" id="prix-default-option-1">
                8.90<sup>€</sup>
            </p>

            <p class="prix-options" id="prix-options-1">

            </p>
        </div>
    </div>

    <div class="row border opt" id="optPiano">
        <div class="select-icon col-md-1 col-sm-2">
            <div class="checkbox checkbox-success checkbox-single">
                <input type="checkbox" id="checkboxGarantieBas" value="Basique"  aria-label="Single checkbox Two">
                <label></label>
            </div>
        </div>
        <div class="picture col-md-2 col-sm-10">
            <img src="" alt="Piano"
                class="img-responsive">
        </div>
        <div class="col-md-7 col-sm-12">
            <div class="col-md-12 no-padding">
                <h2>Piano</h2>
            </div>
            <div class="col-md-12 no-padding">
                <div class="col-md-9 mx-auto">
                    <p class="w-100">Avec le Piano, finie la corvée de repassage ou les dépenses de
                        pressing après le
                        déménagement.
                        Mise à disposition d’une penderie en plastique robuste et facile à transporter pendant la
                        prestation.
                        Dimensions (intérieur) : 50 x 50 x 100 cm
                        Placez y jusqu’à 20 chemises, 10 costumes complets ou encore 10 manteaux
                        (Matériel récupéré à l'issue de la prestation)</p>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <form action="#" method="post" class="cart_1" id="add_service">
                <input type="hidden" id="id_send" value="1">
                <div class="form-group">
                    <select title="2" id="2" name="option_select_2" class="option_select_details form-control">
                        <option value="0">Aucun</option>
                        <option value="215:Piano - 0 étage - 250€">0 étage</option>
                        <option value="216:Piano - 1 étage - 264€">1 étage</option>
                        <option value="217:Piano - 2 étages - 288€ ">2 étages</option>
                        <option value="218:Piano - 3 étages - 336€ ">3 étages</option>
                        <option value="219:Piano - 4 étages - 360€ ">4 étages</option>
                        <option value="220:Piano - 5 étages - 384€ ">5 étages</option>
                        <option value="221:Piano - 6 étages - 408€">6 étages</option>
                        <option value="222:Piano - 7 étages - 432€">7 étages</option>
                        <option value="223:Piano - 8 étages - 456€">8 étages</option>
                        <option value="224:Piano - 9 étages - 480€">9 étages</option>
                        <option value="225:Piano - 10 étages - 504€">10 étages</option>
                    </select>
                </div>
            </form>

            <p class="prix-options" id="prix-default-option-1">
                8.90<sup>€</sup>
            </p>

            <p class="prix-options" id="prix-options-1">

            </p>
        </div>
    </div>

    <div class="row border opt" id="optPenderie">
        <div class="select-icon col-md-1 col-sm-2">
            <div class="checkbox checkbox-success checkbox-single">
                <input type="checkbox" id="checkboxGarantieBas" value="Basique"  aria-label="Single checkbox Two">
                <label></label>
            </div>
        </div>
        <div class="picture col-md-2 col-sm-10">
            <img src="" alt="Transport en penderie"
                class="img-responsive">
        </div>
        <div class="col-md-7 col-sm-12">
            <div class="col-md-12 no-padding">
                <h2>Transport en penderie</h2>
            </div>
            <div class="col-md-12 no-padding">
                <div class="col-md-9 mx-auto">
                    <p class="w-100">Avec le transport en penderie, finie la corvée de repassage ou les dépenses de
                        pressing après le
                        déménagement.
                        Mise à disposition d’une penderie en plastique robuste et facile à transporter pendant la
                        prestation.
                        Dimensions (intérieur) : 50 x 50 x 100 cm
                        Placez y jusqu’à 20 chemises, 10 costumes complets ou encore 10 manteaux
                        (Matériel récupéré à l'issue de la prestation)</p>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <form action="#" method="post" class="cart_1" id="add_service">
                <input type="hidden" id="id_send" value="1">
                <div class="form-group">
                    <select title="1" id="1" name="option_select_1" class="option_select_details form-control">
                        <option value="0">Aucun</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                    </select>
                </div>
            </form>

            <p class="prix-options" id="prix-default-option-1">
                8.90<sup>€</sup>
            </p>

            <p class="prix-options" id="prix-options-1">

            </p>
        </div>
    </div>

    <div class="row border opt" id="OptEmball">
        <div class="select-icon col-md-1 col-sm-2">
            <div class="checkbox checkbox-success checkbox-single">
                <input type="checkbox" id="checkboxGarantieBas" value="Basique"  aria-label="Single checkbox Two">
                <label></label>
            </div>
        </div>
        <div class="picture col-md-2 col-sm-10">
            <img src="" alt="Transport en penderie"
                class="img-responsive">
        </div>
        <div class="col-md-7 col-sm-12">
            <div class="col-md-12 no-padding">
                <h2>Transport en penderie</h2>
            </div>
            <div class="col-md-12 no-padding">
                <div class="col-md-9 mx-auto">
                    <p class="w-100">Avec le transport en penderie, finie la corvée de repassage ou les dépenses de
                        pressing après le
                        déménagement.
                        Mise à disposition d’une penderie en plastique robuste et facile à transporter pendant la
                        prestation.
                        Dimensions (intérieur) : 50 x 50 x 100 cm
                        Placez y jusqu’à 20 chemises, 10 costumes complets ou encore 10 manteaux
                        (Matériel récupéré à l'issue de la prestation)</p>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <form action="#" method="post" class="cart_1" id="add_service">
                <input type="hidden" id="id_send" value="1">
                <div class="form-group">
                    <select title="1" id="1" name="option_select_1" class="option_select_details form-control">
                        <option value="">Aucun</option>
                        <option value="Oui">Oui</option>
                        <option value="Non">Non</option>
                    </select>
                </div>
            </form>

            <p class="prix-options" id="prix-default-option-1">
                8.90<sup>€</sup>
            </p>

            <p class="prix-options" id="prix-options-1">

            </p>
        </div>
    </div>

    <div class="row border opt" id="optCart1">
        <div class="select-icon col-md-1 col-sm-2">
            <div class="checkbox-estimateur">
                <div class="checkbox checkbox-success checkbox-single">
                    <input type="checkbox" id="checkboxGarantieBas" value="Basique"  aria-label="Single checkbox Two">
                    <label></label>
                </div>
            </div>
        </div>
        <div class="picture col-md-2 col-sm-10">
            <img src="" alt="Carton1"
                class="img-responsive">
        </div>
        <div class="col-md-7 col-sm-12">
            <div class="col-md-12 no-padding">
                <h2>Pack Carton n°1</h2>
            </div>
            <div class="col-md-12 no-padding">
                <div class="col-md-9 mx-auto">
                    <p class="w-100">Avec le transport en penderie, finie la corvée de repassage ou les dépenses de
                        pressing après le
                        déménagement.
                        Mise à disposition d’une penderie en plastique robuste et facile à transporter pendant la
                        prestation.
                        Dimensions (intérieur) : 50 x 50 x 100 cm
                        Placez y jusqu’à 20 chemises, 10 costumes complets ou encore 10 manteaux
                        (Matériel récupéré à l'issue de la prestation)</p>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <form action="#" method="post" class="cart_1" id="add_service">
                <input type="hidden" id="id_send" value="1">
                <div class="form-group">
                    <select title="1" id="1" name="option_select_1" class="option_select_details form-control">
                        <option value="0">Aucun</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                    </select>
                </div>
            </form>

            <p class="prix-options" id="prix-default-option-1">
                8.90<sup>€</sup>
            </p>

            <p class="prix-options" id="prix-options-1">

            </p>
        </div>
    </div>

    <div class="row border opt" id="optCart2">
        <div class="select-icon col-md-1 col-sm-2">
            <div class="checkbox-estimateur">
                <div class="checkbox checkbox-success checkbox-single">
                    <input type="checkbox" id="checkboxGarantieBas" value="Basique"  aria-label="Single checkbox Two">
                    <label></label>
                </div>
            </div>
        </div>
        <div class="picture col-md-2 col-sm-10">
            <img src="" alt="Carton2"
                class="img-responsive">
        </div>
        <div class="col-md-7 col-sm-12">
            <div class="col-md-12 no-padding">
                <h2>Pack Carton n°2</h2>
            </div>
            <div class="col-md-12 no-padding">
                <div class="col-md-9 mx-auto">
                    <p class="w-100">Avec le transport en penderie, finie la corvée de repassage ou les dépenses de
                        pressing après le
                        déménagement.
                        Mise à disposition d’une penderie en plastique robuste et facile à transporter pendant la
                        prestation.
                        Dimensions (intérieur) : 50 x 50 x 100 cm
                        Placez y jusqu’à 20 chemises, 10 costumes complets ou encore 10 manteaux
                        (Matériel récupéré à l'issue de la prestation)</p>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <form action="#" method="post" class="cart_1" id="add_service">
                <input type="hidden" id="id_send" value="1">
                <div class="form-group">
                    <select title="1" id="1" name="option_select_1" class="option_select_details form-control">
                        <option value="0">Aucun</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                    </select>
                </div>
            </form>

            <p class="prix-options" id="prix-default-option-1">
                8.90<sup>€</sup>
            </p>

            <p class="prix-options" id="prix-options-1">

            </p>
        </div>
    </div>

    <div class="row border opt" id="optCart3">
        <div class="select-icon col-md-1 col-sm-2">
                <div class="checkbox checkbox-success checkbox-single">
                    <input type="checkbox" id="checkboxGarantieBas" value="Basique"  aria-label="Single checkbox Two">
                    <label></label>
                </div>
        </div>
        <div class="picture col-md-2 col-sm-10">
            <img src="" alt="Pack Carton n°3"
                class="img-responsive">
        </div>
        <div class="col-md-7 col-sm-12">
            <div class="col-md-12 no-padding">
                <h2>Pack Carton n°3</h2>
            </div>
            <div class="col-md-12 no-padding">
                <div class="col-md-9 mx-auto">
                    <p class="w-100">Avec le transport en penderie, finie la corvée de repassage ou les dépenses de
                        pressing après le
                        déménagement.
                        Mise à disposition d’une penderie en plastique robuste et facile à transporter pendant la
                        prestation.
                        Dimensions (intérieur) : 50 x 50 x 100 cm
                        Placez y jusqu’à 20 chemises, 10 costumes complets ou encore 10 manteaux
                        (Matériel récupéré à l'issue de la prestation)</p>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <form action="#" method="post" class="cart_1" id="add_service">
                <input type="hidden" id="id_send" value="1">
                <div class="form-group">
                    <select title="1" id="1" name="option_select_1" class="option_select_details form-control">
                        <option value="0">Aucun</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                    </select>
                </div>
            </form>

            <p class="prix-options" id="prix-default-option-1">
                8.90<sup>€</sup>
            </p>

            <p class="prix-options" id="prix-options-1">

            </p>
        </div>
    </div>

</div>
