<div class="col-md-12 mb-5">
    <h2 class="tunnel">Taille du camion</h2>
    <h4 class="">Tous nos véhicules sont <span class="orange">spécialisés et équipés
            spécifiquement pour le déménagement.</span></h4>

    <div class="alert alert-danger fade in" style="display:none;">
        <i data-dismiss="alert" class="icon-remove close"></i>
        <strong></strong>
    </div>

    <div class="row col-md-12 col-xs-12 d-flex justify-content-between">
        <div class="col-md-4 col-xs-12 no-padding hover-bloc-transport-noselect" id="hover-bloc-transport-1">
            <div class="div-bloc-transport bloc-transport-1 no-margin no-padding no-border no-box-shadow" id="bloc-transport-1"
                style="box-shadow:none;">
                <div class="picture ">
                    <img src="" class="img-responsive img-center" alt="">
                </div>
                <h2 class="text-center text-orange">12m<sup>3</sup></h2>
                <input type="radio" name="taille-camion" class="radio-taille-camion" id="radio-taille-camion-12" data-price="0" data-hiddenprice="100" data-id="radio-taille-camion" data-label="Camion 12m³"
                    value="5">
            </div>
        </div>
        <div class="col-md-4 col-xs-12 no-padding bottom_responsive_30 hover-bloc-transport" id="hover-bloc-transport-2">
            <div class="div-bloc-transport bloc-transport-2 no-margin no-padding  no-border no-box-shadow" id="bloc-transport-2"
                style="box-shadow:none;">
                <div class="picture ">
                    <img src="" class="img-responsive img-center" alt="">
                </div>
                <h2 class="text-center text-orange">22m<sup>3</sup></h2>
                <input type="radio" name="taille-camion" class="radio-taille-camion" id="radio-taille-camion-22" data-price="0" data-hiddenprice="160" data-id="radio-taille-camion" data-label="Camion 22m³"
                    value="5">
            </div>
        </div>
        <div class="col-md-4 col-xs-12 hover-bloc-transport-noselect no-padding" id="hover-bloc-transport-3">
            <div class="div-bloc-transport bloc-transport-3 no-margin no-padding no-border no-box-shadow" id="bloc-transport-3"
                style="box-shadow:none;">
                <div class="picture ">
                    <img src="" class="img-responsive img-center" alt="">
                </div>
                <h2 class="text-center text-orange">40m<sup>3</sup></h2>
                <input type="radio" name="taille-camion" class="radio-taille-camion" id="radio-taille-camion-40" data-price="0" data-hiddenprice="320" data-id="radio-taille-camion" data-label="Camion 40m³"
                    value="5">
            </div>
        </div>
    </div>
</div>

<div class="col-md-6 mx-auto mb-5 d-flex justify-content-around">
        <div>
            <input type="radio" name="taille-camion" class="radio-taille-camion-0" value="none" id="radio-taille-camion-0" data-id="radio-taille-camion" >
            <label for="radio-taille-camion-0" class="ml-3"> Je n'ai pas besoin de camion</label>
        </div>
</div>

<div class="row col-md-12 col-xs-12">
    <div class="col-md-8" style="padding-right:20px;">
        <div class="hidden-xs">
            <h4>L'astuce pour vous aider dans votre choix :</h4>
            <p style="text-align: justify; ">Si vous hésitez entre les deux tailles de camion,
                prenez la taille la plus grande, cela vous évitera de perdre du temps à faire des
                allers-retours.</p>
            <p>Selon nos disponibilités, un camion de 40m3 pourra être remplacé par deux camions de
                20m3</p>
        </div>
    </div>
    <div class="col-md-4 cas-pratique">
        <h4 class="text-orange"><i class="fa fa-lightbulb"></i> CAS PRATIQUE</h4>
        <p class="text-orange">Vous connaissez la surface du logement à déménager ? Alors divisez
            ce chiffre par deux et vous obtenez le volume moyen. (Ceci est une moyenne et peut
            varier selon le type d'objets à transporter). Exemple: pour un deux pièces de 40 m2, un
            camion de 22m3 devrait suffire. </p>
    </div>
</div>

<script>
  var OKButton;
            setTimeout(() => {
            OKButton = $('#tailleCamionForm .slideform-btn-next');
            OKButton.on('click', e => {
                let qty = Cart.getFullItem('taille_camion').quantity;
                let id = Cart.getFullItem('taille_camion').id;
                let uid = localStorage.getItem('uid');
              if(!Cart.getItem("taille_camion") && document.getElementById('radio-taille-camion-0').checked != true){
                $("#tailleCamionFailModal").modal("show");
              }else{
                $.ajax({
                  method: "POST",
                  url: "includes/contact/ajax-devis.php",
                  data: { qty: qty, id: id, uid: uid}
                })

              }
            }); },2000);
  </script>
