<div class="col-md-12">

    <form method="post" id="addForm" class="wpcf7-form" novalidate>

        <div class="slide-title">
            <h2>Adresses du déménagement</h2>
        </div>
        <div id="depBox">

            <h5 class="heading font-size-30 mb-1">Départ</h5>
            <span class="form-group">
                <div id="locationField">
                    <input id="autocomplete" placeholder="Adresse *" onFocus="geolocate()" type="text" tabindex="1"
                        name="addressDep" value="" class="wpcf7-form-control" required />
                </div>
            </span>
            <div class="row">
                <span class="form-group col-md-6">
                    <input type="text" tabindex="2" id="postal_code" name="cpDep" value="" class="wpcf7-form-control"
                        placeholder="Code postal *" required>
                </span>
                <span class="form-group col-md-6">
                    <input type="text" tabindex="3" id="locality" name="cityDep" value="" class="wpcf7-form-control"
                        placeholder="Ville *" required>
                </span>
            </div>
            <div class="row">
                <span class="form-group col-md-6">
                    <select name="typeDep" id="typeDep" class="wpcf7-form-control" required>
                        <option selected disabled>Type... *</option>
                        <option value="Appartement">Appartement</option>
                        <option value="Maison">Maison</option>
                        <option value="Garde-meuble">Garde-meuble</option>
                    </select>
                </span>

                <span class="form-group col-md-6">
                    <div class="input-group">
                        <input type="number" tabindex="3" id="surfaceDep" name="surfaceDep" value=""
                            class="wpcf7-form-control form-control" placeholder="Surface m³" required>
                        <div class="input-group-append">
                            <span class="input-group-text mb-0">m³</span>
                        </div>
                    </div>
                </span>
            </div>

            <div data-condition="input.typeDep == 'Appartement'" class="col-12 p-0" style="display: none;">
                <div class="row">
                    <div class="options options-buttons col-6">
                        <select name="etageAppDep" id="etageAppDep" required>
                            <option disabled selected value="" placeholder="">Etage</option>
                            <option value="RDC">RDC</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                            <option value="13">13</option>
                            <option value="14">14</option>
                            <option value="15">15</option>
                            <option value="16">16</option>
                            <option value="17">17</option>
                            <option value="18">18</option>
                            <option value="19">19</option>
                            <option value="20">20</option>
                        </select>
                    </div>

                    <div class="options options-buttons col-6">
                        <select name="ascAppDep" id="ascAppDep" required>
                            <option disabled selected value="" placeholder="">Ascenseur *</option>
                            <option value="yes">Oui</option>
                            <option value="no">Non</option>
                        </select>

                        <div data-condition="input.ascAppDep == 'yes'" style="display: none;">
                            <select name="sizeAscAppDep" id="sizeAscAppDep" required>
                                <option disabled selected value="" placeholder="">Séléctionnez la place
                                    maximale</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="6+">6+</option>
                            </select>
                        </div>
                    </div>

                </div>

                <div class="row">

                    <div class="options options-buttons col-6">
                        <select name="caveAppDep" id="caveAppDep" required>
                            <option disabled selected value="" placeholder="">Cave *</option>
                            <option value="yes">Oui</option>
                            <option value="no">Non</option>
                        </select>
                    </div>
                    <div class="options options-buttons col-6">
                        <select name="monteAppDep" id="monteAppDep" required>
                            <option disabled selected value="" placeholder="">Monte-charge *</option>
                            <option value="yes">Oui</option>
                            <option value="no">Non</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="options options-buttons col-12">
                        <h3 class="mb-0 mt-2">Distance logement / rue</h3>
                        <input id="distAppDep" required />
                    </div>
                </div>
            </div>

            <div data-condition="input.typeDep == 'Maison'" class="col-12 p-0" style="display: none;">
                <div class="row">

                    <div class="options options-buttons col-6">
                        <select name="etageHomeDep" id="etageHomeDep" required>
                            <option disabled selected value="" placeholder="">Etage</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                    </div>

                    <div class="options options-buttons col-6">
                        <select name="monteHomeDep" id="monteHomeDep" required>
                            <option disabled selected value="" placeholder="">Monte-charge *</option>
                            <option value="yes">Oui</option>
                            <option value="no">Non</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <select name="gardeHomeDep" id="gardeHomeDep" required>
                            <option disabled selected value="" placeholder="">Garde-meuble *</option>
                            <option value="yes">Oui</option>
                            <option value="no">Non</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="options options-buttons col-12">
                            <h3 class="mb-0 mt-2">Distance logement/rue</h3>
                            <input id="distHomeDep" required />
                        </div>
                    </div>
                </div>

            </div>


            <div data-condition="input.typeDep == 'yes' &amp;&amp;  input.group6 == 'yes'" style="display: none;">
                <p>This message appears after all conditions have been marked as "yes".</p>
            </div>

            <span class="form-group">
                <textarea name="commentDep" tabindex="5" row="5" class="wpcf7-form-control wpcf7-textarea"
                    placeholder="Complément: Batîment, code, porte, autre ..."></textarea>
            </span>



        </div>






        <div id="arrBox">

            <h5 class="heading font-size-30 mb-1 mt-3">Arrivée</h5>
            <span class="form-group">
                <div id="locationField">
                    <input id="autocomplete2" placeholder="Adresse *" onFocus="geolocate()" type="text" tabindex="1"
                        name="addressArr" value="" class="wpcf7-form-control" required />
                </div>
            </span>
            <div class="row">
                <span class="form-group col-md-6">
                    <input type="text" tabindex="2" id="postal_code_2" name="cpArr" value="" class="wpcf7-form-control"
                        placeholder="Code postal *" required>
                </span>
                <span class="form-group col-md-6">
                    <input type="text" tabindex="3" id="locality_2" name="cityArr" value="" class="wpcf7-form-control"
                        placeholder="Ville *" required>
                </span>
            </div>
            <div class="row">
                <span class="form-group col-md-6">
                    <select name="typeArr" id="typeArr" class="wpcf7-form-control" required>
                        <option selected disabled>Type... *</option>
                        <option value="Appartement">Appartement</option>
                        <option value="Maison">Maison</option>
                        <option value="Garde-meuble">Garde-meuble</option>
                    </select>
                </span>

                <span class="form-group col-md-6">
                    <div class="input-group">
                        <input type="number" tabindex="3" id="surfaceArr" name="surfaceArr" value=""
                            class="wpcf7-form-control form-control" placeholder="Surface m³" required>
                        <div class="input-group-append">
                            <span class="input-group-text mb-0">m³</span>
                        </div>
                    </div>
                </span>
            </div>
            <div data-condition="input.typeArr == 'Appartement'" class="col-12 p-0" style="display: none;">
                <div class="row">
                    <div class="options options-buttons col-6 form-group">
                        <select name="etageAppArr" id="etageAppArr" required>
                            <option disabled selected value="" placeholder="">Etage</option>
                            <option value="RDC">RDC</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                            <option value="13">13</option>
                            <option value="14">14</option>
                            <option value="15">15</option>
                            <option value="16">16</option>
                            <option value="17">17</option>
                            <option value="18">18</option>
                            <option value="19">19</option>
                            <option value="20">20</option>
                        </select>
                    </div>

                    <div class="options options-buttons col-6 form-group">
                        <select name="ascAppArr" id="ascAppArr" required>
                            <option disabled selected value="" placeholder="">Ascenseur *</option>
                            <option value="yes">Oui</option>
                            <option value="no">Non</option>
                        </select>

                        <div data-condition="input.ascArr == 'yes'" style="display: none;">
                            <select name="sizeAscAppArr" id="sizeAscAppArr" required>
                                <option disabled selected value="" placeholder="">Séléctionnez la place
                                    maximale</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="6+">6+</option>
                            </select>
                        </div>
                    </div>

                </div>

                <div class="row">

                    <div class="options options-buttons col-6 form-group">
                        <select name="caveAppArr" id="caveAppArr" required>
                            <option disabled selected value="" placeholder="">Cave *</option>
                            <option value="yes">Oui</option>
                            <option value="no">Non</option>
                        </select>
                    </div>
                    <div class="options options-buttons col-6 form-group">
                        <select name="monteAppArr" id="monteAppArr" required>
                            <option disabled selected value="" placeholder="">Monte-charge *</option>
                            <option value="yes">Oui</option>
                            <option value="no">Non</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="options options-buttons col-12">
                        <h3 class="mb-0 mt-2">Distance logement / rue</h3>
                        <input id="distAppArr" required />
                    </div>
                </div>
            </div>

            <div data-condition="input.typeArr == 'Maison'" class="col-12 p-0" style="display: none;">
                <div class="row">

                    <div class="options options-buttons col-6">
                        <select name="etageHomeArr" id="etageHomeArr" required>
                            <option disabled selected value="" placeholder="">Etage</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                    </div>

                    <div class="options options-buttons col-6">
                        <select name="monteHomeArr" id="monteHomeArr" required>
                            <option disabled selected value="" placeholder="">Monte-charge *</option>
                            <option value="yes">Oui</option>
                            <option value="no">Non</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <select name="gardeHomeArr" id="gardeHomeArr" required>
                            <option disabled selected value="" placeholder="">Garde-meuble *</option>
                            <option value="yes">Oui</option>
                            <option value="no">Non</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="options options-buttons col-12">
                            <h3 class="mb-0 mt-2">Distance logement/rue</h3>
                            <input id="distHomeArr" required />
                        </div>
                    </div>
                </div>

            </div>

            <div data-condition="input.typeArr == 'yes' &amp;&amp;  input.group6 == 'yes'" style="display: none;">
                <p>This message appears after all conditions have been marked as "yes".</p>
            </div>


            <span class="form-group">
                <textarea name="commentArr" tabindex="5" row="5" class="wpcf7-form-control wpcf7-textarea"
                    placeholder="Complément: Batîment, code, porte, autre ..."></textarea>
            </span>
        </div>


    </form>
</div>

<script>
    var OKButton;
    setTimeout(() => {

        OKButton = $('.adressesButtonForm .slideform-btn-next')[0];
        OKButton.addEventListener('click', () => {

            console.log(document.getElementById('typeDep').value);

            let tab = [];

            let depInputs = document.getElementById('depBox').getElementsByTagName('input');
            let depSelects = document.getElementById('depBox').getElementsByTagName('select');
            let depTextAreas = document.getElementById('depBox').getElementsByTagName('textarea');

            let arrInputs = document.getElementById('arrBox').getElementsByTagName('input');
            let arrSelects = document.getElementById('arrBox').getElementsByTagName('select');
            let arrTextAreas = document.getElementById('arrBox').getElementsByTagName('textarea');

            for (var i = 0; i < depInputs.length; i++) {
                input = depInputs[i];
                console.log('input:' + input.value)
            }

            for (var i = 0; i < depSelects.length; i++) {
                select = depSelects[i];
                console.log('select:' + select.value)

            }

            for (var i = 0; i < depTextAreas.length; i++) {
                textArea = depTextAreas[i];
                console.log('textArea:' + textArea.value)
            }

            for (var i = 0; i < tab.length; i++) {
                tabs = tab[i];
            }

            Cart.addItem({
                id: "adresseDep",
                label: "Adresse de départ",

                price: 0,
            })

            Cart.addItem({
                id: "adresseArr",
                label: "Adresse d'arrivée'",
            })




        });
    }, 2000);


    /*  $(function() {

         $( ".slideform-btn" ).submit(function( event ) {
         if ( $( "input:first" ).val() === "correct" ) {
             $( "span" ).text( "Validated..." ).show();
             return;
         }
         });

         $('').on('click', () => {

         });

             $('input[name="addressDep"]').on('click', () => {
                 document.getElementById('autocomplete').readOnly = false;
             });

             $('input[name="addressDep"]').on('blur', () => {
                 document.getElementById('autocomplete').readOnly = true;
             });

             $('input[name="addressArr"]').on('click', () => {
                 document.getElementById('autocomplete2').readOnly = false;
             });

             $('input[name="addressArr"]').on('blur', () => {
                 document.getElementById('autocomplete2').readOnly = true;
             });

     }); */
</script>
