<div class="col-xs-12">
	<h2 class="slide-title">
		Besoin de matériel ?
	</h2>
</div>

<div class="sticker-calculator col-md-12">


<div class="col-md-12 row liste-matos">
		<div class="col-md-3 col-sm-6 ">
			<div class="list-materiel-2">
				<div class="materiel-2 ">
					<div class="col-md-12 col-xs-12  no-padding details-shop-description">
						<h3 class="name">Bulle de protection</h3>
						<p class="text-center">
						</p>
					</div>
					<div class=" img-carton-responsive">
					</div>
				</div>
				<div class="col-md-12 col-xs-12 no-padding add-panier-2">
					<div action="#" method="post" class="cart_8" id="add_materiel_details">
						<input type="hidden" id="id_send" value="8">
						<div class="col-md-8 col-xs-8 pdlr0">
							<div class="form-group">
								<input type="button" class="plus_moins minus" value="-" data-id="8">
								<input type="text" class="input-text qty text" disabled=""  value="0"
									name="quantite" id="quantite_8" min="0" step="1">
								<input type="button" class="plus_moins plus" value="+" data-id="8" datal-label="Bulle de protection" data-price="9.90">
							</div>
						</div>
						<div class="col-md-4 col-xs-4 prix pdl0" style="line-height:30px;">
							9.90 €
						</div>
					</div>
				</div>
				<br clear="all">
			</div>
		</div>
		<div class="col-md-3 col-sm-6 ">
			<div class="list-materiel-2">
				<div class="materiel-2 ">
					<div class="col-md-12 col-xs-12  no-padding details-shop-description">
						<h3 class="name">Carton Standard</h3>
						<p class="text-center">
							Dimensions : 55 x 35 x 30 cm </p>
						</div>
										<div class=" img-carton-responsive">
										</div>
				</div>
				<div class="col-md-12 col-xs-12 no-padding add-panier-2">
					<div action="#" method="post" class="cart_100" id="add_materiel_details">
						<input type="hidden" id="id_send" value="100">
						<div class="col-md-8 col-xs-8 pdlr0">
							<div class="form-group">
								<input type="button" class="plus_moins minus" value="-" data-id="100">
								<input type="text" class="input-text qty text" disabled=""  value="0"
									name="quantite" id="quantite_100" min="0" step="1">
								<input type="button" class="plus_moins plus" value="+" data-id="100" datal-label="Carton standard" data-price="9.90">
							</div>
						</div>
						<div class="col-md-4 col-xs-4 prix pdl0" style="line-height:30px;">
							1.80 €
						</div>
					</div>
				</div>
				<br clear="all">
			</div>
		</div>
		<div class="col-md-3 col-sm-6 ">
			<div class="list-materiel-2">
				<div class="materiel-2 ">
					<div class="col-md-12 col-xs-12  no-padding details-shop-description">
						<h3 class="name">Carton Livres</h3>
						<p class="text-center">
							Dimensions : 35 x 34 x 27 cm </p>
						</div>
										<div class=" img-carton-responsive">
										</div>
				</div>
				<div class="col-md-12 col-xs-12 add-panier-2">
					<div action="#" method="post" class="cart_101" id="add_materiel_details">
						<input type="hidden" id="id_send" value="101">
						<div class="col-md-8 col-xs-8 pdlr0">
							<div class="form-group">
								<input type="button" class="plus_moins minus" value="-" data-id="101">
								<input type="text" class="input-text qty text" disabled=""  value="0"
									name="quantite" id="quantite_101" min="0" step="1">
								<input type="button" class="plus_moins plus" value="+" data-id="101" datal-label="Carton livres" data-price="9.90">
							</div>
						</div>
						<div class="col-md-4 col-xs-4 prix pdl0" style="line-height:30px;">
							1.00 €
						</div>
					</div>
				</div>
				<br clear="all">
			</div>
		</div>
		<div class="col-md-3 col-sm-6 ">
			<div class="list-materiel-2">
				<div class="materiel-2 ">
					<div class="col-md-12 col-xs-12  no-padding details-shop-description">
						<h3 class="name">Carton XL</h3>
						<p class="text-center">
							Dimensions : 57 x 45 x 45 cm </p>
						</div>
										<div class=" img-carton-responsive">
										</div>
				</div>
				<div class="col-md-12 col-xs-12 no-padding add-panier-2">
					<div action="#" method="post" class="cart_102" id="add_materiel_details">
						<input type="hidden" id="id_send" value="102">
						<div class="col-md-8 col-xs-8 pdlr0">
							<div class="form-group">
								<input type="button" class="plus_moins minus" value="-" data-id="102">
								<input type="text" class="input-text qty text" disabled=""  value="0"
									name="quantite" id="quantite_102" min="0" step="1">
								<input type="button" class="plus_moins plus" value="+" data-id="102" datal-label="Carton XL" data-price="9.90">
							</div>
						</div>
						<div class="col-md-4 col-xs-4 prix pdl0" style="line-height:30px;">
							3.50 €
						</div>
					</div>
				</div>
				<br clear="all">
			</div>
		</div>
		<div class="col-md-3 col-sm-6 ">
			<div class="list-materiel-2">
				<div class="materiel-2 ">
					<div class="col-md-12 col-xs-12  no-padding details-shop-description">
						<h3 class="name">Carton 12 bouteilles</h3>
						<p class="text-center">
							Dimensions : 35 x 34 x 27 cm </p>
						</div>
						<div class=" img-carton-responsive">
						</div>
					</div>
					<div class="col-md-12 col-xs-12 no-padding add-panier-2">
						<div action="#" method="post" class="cart_103" id="add_materiel_details">
							<input type="hidden" id="id_send" value="103">
						<div class="col-md-8 col-xs-8 pdlr0">
							<div class="form-group">
								<input type="button" class="plus_moins minus" value="-" data-id="103">
								<input type="text" class="input-text qty text" disabled=""  value="0"
									name="quantite" id="quantite_103" min="0" step="1">
								<input type="button" class="plus_moins plus" value="+" data-id="103" datal-label="Carton 12 bouteilles" data-price="9.90">
							</div>
						</div>
						<div class="col-md-4 col-xs-4 prix pdl0" style="line-height:30px;">
							5.00 €
						</div>
					</div>
				</div>
				<br clear="all">
			</div>
		</div>
		<div class="col-md-3 col-sm-6 ">
			<div class="list-materiel-2">
				<div class="materiel-2 ">
					<div class="col-md-12 col-xs-12  no-padding details-shop-description">
						<h3 class="name">Carton 24 verres</h3>
						<p class="text-center">
							Dimensions : 35 x 34 x 27 cm </p>
						</div>
										<div class=" img-carton-responsive">
										</div>
				</div>
				<div class="col-md-12 col-xs-12 no-padding add-panier-2">
					<div action="#" method="post" class="cart_104" id="add_materiel_details">
						<input type="hidden" id="id_send" value="104">
						<div class="col-md-8 col-xs-8 pdlr0">
							<div class="form-group">
								<input type="button" class="plus_moins minus" value="-" data-id="104">
								<input type="text" class="input-text qty text" disabled=""  value="0"
									name="quantite" id="quantite_104" min="0" step="1">
								<input type="button" class="plus_moins plus" value="+" data-id="104" datal-label="Carton 24 verres" data-price="9.90">
							</div>
						</div>
						<div class="col-md-4 col-xs-4 prix pdl0" style="line-height:30px;">
							5.00 €
						</div>
					</div>
				</div>
				<br clear="all">
			</div>
		</div>
		<div class="col-md-3 col-sm-6 ">
			<div class="list-materiel-2">
				<div class="materiel-2 ">
					<div class="col-md-12 col-xs-12  no-padding details-shop-description">
						<h3 class="name">Carton 8 assiettes</h3>
						<p class="text-center">
							Dimensions : 35 x 34 x 27 cm </p>
						</div>
										<div class=" img-carton-responsive">
										</div>
				</div>
				<div class="col-md-12 col-xs-12 no-padding add-panier-2">
					<div action="#" method="post" class="cart_105" id="add_materiel_details">
						<input type="hidden" id="id_send" value="105">
						<div class="col-md-8 col-xs-8 pdlr0">
							<div class="form-group">
								<input type="button" class="plus_moins minus" value="-" data-id="105">
								<input type="text" class="input-text qty text" disabled=""  value="0"
									name="quantite" id="quantite_105" min="0" step="1">
								<input type="button" class="plus_moins plus" value="+" data-id="105" datal-label="Carton 8 assiettes" data-price="9.90">
							</div>
						</div>
						<div class="col-md-4 col-xs-4 prix pdl0" style="line-height:30px;">
							5.00 €
						</div>
					</div>
				</div>
				<br clear="all">
			</div>
		</div>
		<div class="col-md-3 col-sm-6 ">
			<div class="list-materiel-2">
				<div class="materiel-2 ">
					<div class="col-md-12 col-xs-12  no-padding details-shop-description">
						<h3 class="name">Carton Penderie</h3>
						<p class="text-center">
							Dimensions : 100 x 50 x 50 cm </p>
						</div>
										<div class=" img-carton-responsive">
										</div>
				</div>
				<div class="col-md-12 col-xs-12 no-padding add-panier-2">
					<div action="#" method="post" class="cart_106" id="add_materiel_details">
						<input type="hidden" id="id_send" value="106">
						<div class="col-md-8 col-xs-8 pdlr0">
							<div class="form-group">
								<input type="button" class="plus_moins minus" value="-" data-id="106">
								<input type="text" class="input-text qty text" disabled=""  value="0"
									name="quantite" id="quantite_106" min="0" step="1">
								<input type="button" class="plus_moins plus" value="+" data-id="106" datal-label="Carton penderie" data-price="9.90">
							</div>
						</div>
						<div class="col-md-4 col-xs-4 prix pdl0" style="line-height:30px;">
							13.90 €
						</div>
					</div>
				</div>
				<br clear="all">
			</div>
		</div>
		<div class="col-md-3 col-sm-6 ">
			<div class="list-materiel-2">
				<div class="materiel-2 ">
					<div class="col-md-12 col-xs-12  no-padding details-shop-description">
						<h3 class="name">Adhésif Standard</h3>
						<p class="text-center">
							</p>
						</div>
										<div class=" img-carton-responsive">
										</div>
				</div>
				<div class="col-md-12 col-xs-12 no-padding add-panier-2">
					<div action="#" method="post" class="cart_200" id="add_materiel_details">
						<input type="hidden" id="id_send" value="200">
						<div class="col-md-8 col-xs-8 pdlr0">
							<div class="form-group">
								<input type="button" class="plus_moins minus" value="-" data-id="200" >
								<input type="text" class="input-text qty text" disabled=""  value="0"
									name="quantite" id="quantite_200" min="0" step="1">
								<input type="button" class="plus_moins plus" value="+" data-id="200"  datal-label="Adhésif Standard" data-price="9.90">
							</div>
						</div>
						<div class="col-md-4 col-xs-4 prix pdl0" style="line-height:30px;">
							2.90 €
						</div>
					</div>
				</div>
				<br clear="all">
			</div>
		</div>
		<div class="col-md-3 col-sm-6 ">
			<div class="list-materiel-2">
				<div class="materiel-2 ">
					<div class="col-md-12 col-xs-12  no-padding details-shop-description">
						<h3 class="name">Marqueur noir</h3>
						<p class="text-center">
							</p>
						</div>
										<div class=" img-carton-responsive">
										</div>
				</div>
				<div class="col-md-12 col-xs-12 no-padding add-panier-2">
					<div action="#" method="post" class="cart_201" id="add_materiel_details">
						<input type="hidden" id="id_send" value="201">
						<div class="col-md-8 col-xs-8 pdlr0">
							<div class="form-group">
								<input type="button" value="-"  data-id="201" class='plus_moins minus'>
								<input type="text" class="input-text qty text" disabled=""  value="50"
									name="quantite" id="quantite_201" min="0" step="1">
								<input type="button" value="+" data-id="201" class='plus_moins plus' data-label='Marqueur noir' data-price='43'>
							</div>
						</div>
						<div class="col-md-4 col-xs-4 prix pdl0" style="line-height:30px;">
							3.00 €
						</div>
					</div>
				</div>
				<br clear="all">
			</div>
		</div>
		<div class="col-md-3 col-sm-6 ">
			<div class="list-materiel-2">
				<div class="materiel-2 ">
					<div class="col-md-12 col-xs-12  no-padding details-shop-description">
						<h3 class="name">Dévidoir pour adhésif</h3>
						<p class="text-center">
							</p>
						</div>
										<div class=" img-carton-responsive">
										</div>
				</div>
				<div class="col-md-12 col-xs-12 no-padding add-panier-2">
					<div action="#" method="post" class="cart_202" id="add_materiel_details">
						<input type="hidden" id="id_send" value="202">
						<div class="col-md-8 col-xs-8 pdlr0">
							<div class="form-group">
								<input type="button" class="plus_moins minus" value="-" data-id="202">
								<input type="text" class="input-text qty text" disabled=""  value="0"
									name="quantite" id="quantite_202" min="0" step="1">
								<input type="button" class="plus_moins plus" value="+" data-id="202" datal-label="Dévidoir pour adhésif">
							</div>
						</div>
						<div class="col-md-4 col-xs-4 prix pdl0" style="line-height:30px;">
							12.00 €
						</div>
					</div>
				</div>
				<br clear="all">
			</div>
		</div>
		<div class="col-md-3 col-sm-6 ">
			<div class="list-materiel-2">
				<div class="materiel-2 ">
					<div class="col-md-12 col-xs-12  no-padding details-shop-description">
						<h3 class="name">Housse de matelas PVC</h3>
						<p class="text-center">
							</p>
									<div class=" img-carton-responsive">
									</div>
					</div>
				</div>
				<div class="col-md-12 col-xs-12 no-padding add-panier-2">
					<div action="#" method="post" class="cart_203" id="add_materiel_details">
						<input type="hidden" id="id_send" value="203">
						<div class="col-md-8 col-xs-8 pdlr0">
							<div class="form-group">
								<input type="button" class="plus_moins minus" value="-" data-id="203">
								<input type="text" class="input-text qty text" disabled=""  value="0"
									name="quantite" id="quantite_203" min="0" step="1">
								<input type="button" class="plus_moins plus" value="+" data-id="203" datal-label="Housse de matelas PVC">
							</div>
						</div>
						<div class="col-md-4 col-xs-4 prix pdl0" style="line-height:30px;">
							5.90 €
						</div>
					</div>
				</div>
				<br clear="all">
			</div>
		</div>
	</div>

	<div class="col-md-12 div_livraison_materiel" style="display: block;">
			<h2 class="">Réception de mon matériel</h2>
		<div class="col-md-12 row">
			<div class="col-md-4 col-xd-4 row_livraison" id="livraison_1">
				<div class="row_border_livraison border-gris-livraison">
					<label style="font-size: 1em; margin-bottom:0;" class="radio-inline">
						<input type="radio" name="option_livraison" class="checkbox_livraison" id="checkbox_livraison_1" data-price="19.90" data-id="checkbox_livraison_1" data-label="Livraison à domicile"
							value="1">
						Livraison à domicile <br>
						Coût de l’option : <span class="text-orange">19.90€</span>
					</label>
				</div>
			</div>
			<div class="col-md-4 col-xd-4 row_livraison" id="livraison_4">
				<div class="row_border_livraison border-gris-livraison">
					<label style="font-size: 1em; margin-bottom:0;" class="radio-inline">
						<input type="radio" name="option_livraison" class="checkbox_livraison" id="checkbox_livraison_4" data-price="0" data-id="checkbox_livraison_1" data-label="Retrait en agence"
							value="4">
						Retrait en agence <br>
						Coût de l’option : <span class="text-orange">Gratuit</span>
					</label>
				</div>
			</div>
			<div class="col-md-4 col-xd-4 row_livraison" id="livraison_2">
				<div class="row_border_livraison border-gris-livraison">
					<label style="font-size: 1em; margin-bottom:0;" class="radio-inline">
						<input type="radio" name="option_livraison" class="checkbox_livraison" id="checkbox_livraison_2" data-price="0" data-id="checkbox_livraison_1" data-label="Livraison le jour du déménagement"
							value="2">
						Livraison le jour du déménagement <br>
						Coût de l’option : <span class="text-orange">Gratuit</span>
					</label>
				</div>
			</div>
			<br clear="all">
		</div>
	</div>

</div>
