<div class="slide-title">
    <h2 class="mb-5"> Montage / Démontage</h2>
</div>
<div class="col-12">
    <div class="row">
        <div class="col-md-6 col-xs-12 border-right">
            <ul id="listObjMontage" class="list-group text-left text-uppercase font-size-15">

            </ul>
        </div>

        <div class="col-md-6 col-xs-12">
            <h5 class="font-size-20">Blog</h5>
            <ul class="list-group">
                <li class="list-group-item">
                    <p><strong>Pourquoi démonter ?</strong> <br>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio soluta harum
                        eveniet, quod dolorem error?
                    </p>
                </li>
                <li class="list-group-item">
                    <p><strong>Quoi démonter ? </strong><br>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt doloribus dolores
                        aspernatur vel. Aspernatur, dolorum!</p>
                </li>
                <li class="list-group-item">
                    <p><strong>Quand démonter ?</strong><br>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt doloribus dolores
                        aspernatur vel. Aspernatur, dolorum!</p>
                </li>
            </ul>
        </div>
    </div>
</div>
