<div class="col-xs-12">
    <h2 class="slide-title">
        Choisir mes options
    </h2>
    <h4>Vos options adaptées à vos besoins</h4>
</div>

<div class="col-md-12">

    <div class="row border opt" id="optMonteMeuble">
        <div class="select-icon col-md-1 col-sm-2">
            <div class="checkbox checkbox-success checkbox-single">
                <input type="checkbox" readonly disabled >
                <label></label>
            </div>
        </div>
        <div class="picture col-md-2 col-sm-10">
            <img src="" alt="Monte meubles"
                class="img-responsive">
        </div>
        <div class="col-md-7 col-sm-12">
            <div class="col-md-12 no-padding">
                <h2>Monte meubles</h2>
            </div>
            <div class="col-md-12 no-padding">
                <div class="col-md-9 mx-auto">
                    <p class="w-100">Avec le Monte meubles, finie la corvée de repassage ou les dépenses de
                        pressing après le
                        déménagement.
                        Mise à disposition d’une penderie en plastique robuste et facile à transporter pendant la
                        prestation.
                        Dimensions (intérieur) : 50 x 50 x 100 cm
                        Placez y jusqu’à 20 chemises, 10 costumes complets ou encore 10 manteaux
                        (Matériel récupéré à l'issue de la prestation)</p>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <form action="#" method="post" class="cart_1" id="add_service">
                <input type="hidden" id="id_send" value="1">
                <div class="form-group">
                    <select title="1" data-id="option_select_1" id="option_select_mm" name="option_select_1" class=" form-control">
                        <option value="0">Aucun</option>
                        <option value="300:Monte meubles avec technicien demi journée (4h max - 1 adresse max)">
                            Demi-journée</option>
                        <option value="500:Monte meubles avec technicien journée entière (7h max - 2 adresses max)">
                            Journee</option>
                    </select>
                </div>
            </form>

            <p class="prix-options" id="prix-default-option-1">
                Demi-journée : 300<sup>€</sup>
            </p>

            <p class="prix-options" id="prix-options-1">
                Journée : 500<sup>€</sup>
            </p>
        </div>
    </div>

    <div class="row border opt" id="optPiano">
        <div class="select-icon col-md-1 col-sm-2">
            <div class="checkbox checkbox-success checkbox-single">
                <input type="checkbox" readonly disabled >
                <label></label>
            </div>
        </div>
        <div class="picture col-md-2 col-sm-10">
            <img src="" alt="Piano"
                class="img-responsive">
        </div>
        <div class="col-md-7 col-sm-12">
            <div class="col-md-12 no-padding">
                <h2>Piano</h2>
            </div>
            <div class="col-md-12 no-padding">
                <div class="col-md-9 mx-auto">
                    <p class="w-100">Avec le Piano, finie la corvée de repassage ou les dépenses de
                        pressing après le
                        déménagement.
                        Mise à disposition d’une penderie en plastique robuste et facile à transporter pendant la
                        prestation.
                        Dimensions (intérieur) : 50 x 50 x 100 cm
                        Placez y jusqu’à 20 chemises, 10 costumes complets ou encore 10 manteaux
                        (Matériel récupéré à l'issue de la prestation)</p>
                </div>
            </div>
        </div>
        <div class="col-md-2">

            <div class="cbr-animation-box animated mt-2"
                style="visibility: visible; animation-delay: 0s; animation-name: fadeInUpSmall;">
                <a href="tel:+33148224610"
                    class="cbr-button px-2 btn-lg font-size-13 out-line-2px button-has-bg-3"><span
                        class="text-uppercase">Nous appeler</span></a>
            </div>

            <!-- <p class="prix-options" id="prix-default-option-1">
                8.90<sup>€</sup>
            </p>

            <p class="prix-options" id="prix-options-1">

            </p> -->
        </div>
    </div>

    <div class="row border opt" id="optPenderie">
        <div class="select-icon col-md-1 col-sm-2">
            <div class="checkbox checkbox-success checkbox-single">
                <input type="checkbox" readonly disabled >
                <label></label>
            </div>
        </div>
        <div class="picture col-md-2 col-sm-10">
            <img src="" alt="Transport en penderie"
                class="img-responsive">
        </div>
        <div class="col-md-7 col-sm-12">
            <div class="col-md-12 no-padding">
                <h2>Transport en penderie</h2>
            </div>
            <div class="col-md-12 no-padding">
                <div class="col-md-9 mx-auto">
                    <p class="w-100">Avec le transport en penderie, finie la corvée de repassage ou les dépenses de
                        pressing après le
                        déménagement.
                        Mise à disposition d’une penderie en plastique robuste et facile à transporter pendant la
                        prestation.
                        Dimensions (intérieur) : 50 x 50 x 100 cm
                        Placez y jusqu’à 20 chemises, 10 costumes complets ou encore 10 manteaux
                        (Matériel récupéré à l'issue de la prestation)</p>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <form action="#" method="post" class="cart_1" id="add_service">
                <input type="hidden" id="id_send" value="1">
                <div class="form-group">
                    <select title="1" data-id="option_select_2" data-label="Transport en penderie" data-price="15" id="1" name="option_select_2" class="option_select_details form-control">
                        <option value="0">Aucun</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                    </select>
                </div>
            </form>

            <p class="prix-options" id="prix-default-option-1">
                15<sup>€</sup>
            </p>

            <p class="prix-options" id="prix-options-1">

            </p>
        </div>
    </div>


    <div class="row border opt" id="optCart1">
        <div class="select-icon col-md-1 col-sm-2">
            <div class="checkbox-estimateur">
                <div class="checkbox checkbox-success checkbox-single">
                    <input type="checkbox" readonly disabled >
                    <label></label>
                </div>
            </div>
        </div>
        <div class="picture col-md-2 col-sm-10">
            <img src="" alt="Carton1"
                class="img-responsive">
        </div>
        <div class="col-md-7 col-sm-12">
            <div class="col-md-12 no-padding">
                <h2>Pack Déménagement T1 - T2</h2>
            </div>
            <div class="col-md-12 no-padding">
                <div class="col-md-9 mx-auto">
                    <p class="w-100">Avec le transport en penderie, finie la corvée de repassage ou les dépenses de
                        pressing après le
                        déménagement.
                        Mise à disposition d’une penderie en plastique robuste et facile à transporter pendant la
                        prestation.
                        Dimensions (intérieur) : 50 x 50 x 100 cm
                        Placez y jusqu’à 20 chemises, 10 costumes complets ou encore 10 manteaux
                        (Matériel récupéré à l'issue de la prestation)</p>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <form action="#" method="post" class="cart_1" id="add_service">
                <div class="form-group">
                    <select  data-id="option_select_4" data-label="Pack Déménagement T1 - T2" data-price="60.25" name="option_select_4" class="option_select_details form-control">
                        <option value="0">Aucun</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                    </select>
                </div>
            </form>

            <p class="prix-options" id="">
                60.25<sup>€</sup>
            </p>

            <p class="prix-options" id="">

            </p>
        </div>
    </div>

    <div class="row border opt" id="optCart2">
        <div class="select-icon col-md-1 col-sm-2">
            <div class="checkbox-estimateur">
                <div class="checkbox checkbox-success checkbox-single">
                    <input type="checkbox" readonly disabled >
                    <label></label>
                </div>
            </div>
        </div>
        <div class="picture col-md-2 col-sm-10">
            <img src="" alt="Carton2"
                class="img-responsive">
        </div>
        <div class="col-md-7 col-sm-12">
            <div class="col-md-12 no-padding">
                <h2>Pack Déménagement T3 - T4</h2>
            </div>
            <div class="col-md-12 no-padding">
                <div class="col-md-9 mx-auto">
                    <p class="w-100">Avec le transport en penderie, finie la corvée de repassage ou les dépenses de
                        pressing après le
                        déménagement.
                        Mise à disposition d’une penderie en plastique robuste et facile à transporter pendant la
                        prestation.
                        Dimensions (intérieur) : 50 x 50 x 100 cm
                        Placez y jusqu’à 20 chemises, 10 costumes complets ou encore 10 manteaux
                        (Matériel récupéré à l'issue de la prestation)</p>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <form action="#" method="post" class="cart_1" id="add_service">
                <input type="hidden" id="id_send" value="1">
                <div class="form-group">
                    <select  data-id="option_select_5" data-label="Pack Déménagement T3 - T4" data-price="133"  name="option_select_5" class="option_select_details form-control">
                        <option value="0">Aucun</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                    </select>
                </div>
            </form>

            <p class="prix-options" id="">
                133<sup>€</sup>
            </p>

            <p class="prix-options" id="">

            </p>
        </div>
    </div>

    <div class="row border opt" id="optCart3">
        <div class="select-icon col-md-1 col-sm-2">
                <div class="checkbox checkbox-success checkbox-single">
                    <input type="checkbox" readonly disabled >
                    <label></label>
                </div>
        </div>
        <div class="picture col-md-2 col-sm-10">
            <img src="" alt="Pack Carton n°3"
                class="img-responsive">
        </div>
        <div class="col-md-7 col-sm-12">
            <div class="col-md-12 no-padding">
                <h2>Pack Déménagement T5 - T6</h2>
            </div>
            <div class="col-md-12 no-padding">
                <div class="col-md-9 mx-auto">
                    <p class="w-100">Avec le transport en penderie, finie la corvée de repassage ou les dépenses de
                        pressing après le
                        déménagement.
                        Mise à disposition d’une penderie en plastique robuste et facile à transporter pendant la
                        prestation.
                        Dimensions (intérieur) : 50 x 50 x 100 cm
                        Placez y jusqu’à 20 chemises, 10 costumes complets ou encore 10 manteaux
                        (Matériel récupéré à l'issue de la prestation)</p>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <form action="#" method="post" class="cart_1" id="add_service">
                <input type="hidden" id="id_send" value="1">
                <div class="form-group">
                    <select  data-id="option_select_6" data-label="Pack Déménagement T5 - T6" data-price="204" name="option_select_6" class="option_select_details form-control">
                        <option value="0">Aucun</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                    </select>
                </div>
            </form>

            <p class="prix-options" id="">
                204<sup>€</sup>
            </p>

            <p class="prix-options" id="">

            </p>
        </div>
    </div>



</div>
