<div class="col-md-12">
    <div class="card-box">
        <div class="clearfix">
            <div class="float-left mb-3">
                <!-- <img src="assets/images/logo.png" alt="" height="28" class="bg-danger"> -->
            </div>
            <div class="float-right">
                <h2 class="m-0 d-print-none">Devis</h2>
            </div>
        </div>


        <div class="row">
            <div class="col-12">
                <div class="mt-3 text-center">
                    <h6 class="font-size-20"><b>Hello,</b></h6>
                    <p class="text-muted">Voici le récapitulatif de votre déménagement Lorem, ipsum
                        dolor sit amet consectetur adipisicing elit. Minima saepe sint sed dicta neque,
                        id suscipit omnis ab veniam dolor.? </p>
                </div>

            </div><!-- end col -->
            <!-- <div class="col-4 offset-2">
                                        <div class="mt-3 float-right">
                                            <p class="m-b-10"><strong>Order Date: </strong> Jan 17, 2016</p>
                                            <p class="m-b-10"><strong>Order Status: </strong> <span class="badge badge-success">Paid</span></p>
                                            <p class="m-b-10"><strong>Order ID: </strong> #123456</p>
                                        </div>
                                    </div> -->
            <!-- end col -->
        </div>
        <!-- end row -->

        <div class="row mt-3">
            <div class="col-6">
                <h6>Adresse de départ</h6>

                <address class="line-h-24">
                    10 rue des blés<br>
                    93210, Saint-Denis<br>
                </address>

            </div>

            <div class="col-6">
                <h6>Adresse d'arrivée</h6>

                <address class="line-h-24">
                    39 rue de la réunion<br>
                    75020, Paris<br>
                </address>

            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table mt-4">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Objet</th>
                                <th>Quantité</th>
                                <th>Prix</th>
                                <th class="text-right">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>
                                    <b>Laptop</b> <br />
                                    Brand Model VGN-TXN27N/B
                                    11.1" Notebook PC
                                </td>
                                <td>1</td>
                                <td>$1799</td>
                                <td class="text-right">$1799</td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>
                                    <b>Warranty</b> <br />
                                    Two Year Extended Warranty -
                                    Parts and Labor
                                </td>
                                <td>3</td>
                                <td>$499</td>
                                <td class="text-right">$1497</td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>
                                    <b>LED</b> <br />
                                    80cm (32) HD Ready LED TV
                                </td>
                                <td>2</td>
                                <td>$412</td>
                                <td class="text-right">$824</td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="clearfix pt-5">
                    <h6 class="text-muted">Notes:</h6>

                    <small>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam odit amet
                        placeat id at soluta,
                        atque doloribus accusantium ratione molestias.
                        Asperiores atque architecto cupiditate, rerum saepe velit illum consequuntur
                        sunt.
                    </small>
                </div>

            </div>
            <div class="col-6">
                <div class="float-right">
                    <p><b>Sous-total:</b> 4120.00€</p>
                    <p><b>TVA 12.5%:</b> 515€</p>
                    <h3>4635.00€</h3>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="hidden-print mt-2 mb-4">
            <div class="row text-right">
                <div class="col-md-10"></div>
                <div class="cbr-animation-box animated col-md-1" style="visibility: visible; animation-delay: 0s; animation-name: fadeInUpSmall;">
                    <a href="#" class="cbr-button p-2 pt-3 btn-sm out-line-2px button-has-bg-3"><span class="text-uppercase">Imprimer</span></a>
                </div>
                <div class="cbr-animation-box animated col-md-1" style="visibility: visible; animation-delay: 0s; animation-name: fadeInUpSmall;">
                    <a href="#" class="cbr-button p-2 pt-3 btn-sm out-line-2px button-has-bg-3"><span class="text-uppercase text-center">Envoyer
                            par mail</span></a>
                </div>
            </div>
        </div>
    </div>

</div>

<hr>

<div class="col-md-12 wpcf7-form">
    <h5 class="heading font-size-30 mb-5">Contact</h5>
    <div class="row">
        <span class="form-group col-md-6">
            <select name="statut" id="statut" class="required wpcf7-form-control">
                <option disabled selected value="">Vous êtes un...</option>
                <option value="0">Particulier</option>
                <option value="1">Professionnel</option>
            </select>
        </span>
        <span class="form-group col-md-6">
            <div class="input-group">
                <select name="source" id="source" class="wpcf7-form-control required">
                    <option value="">Comment nous avez-vous connu ?</option>
                    <option value="20">Agence Atradem</option>
                    <option value="27">Autre</option>
                    <option value="25">Crédit Agricole</option>
                    <option value="19">Flyers</option>
                    <option value="24">MAIF</option>
                    <option value="3">Moteur de recherche (GOOGLE / BING...)</option>
                    <option value="2">Presse</option>
                    <option value="9">Recommandation</option>
                    <option value="16">Réseaux Sociaux (Facebook...)</option>
                    <option value="26">Selectra</option>
                    <option value="17">SNCF</option>
                    <option value="23">GSG Transport Express</option>
                </select>
            </div>
        </span>

    </div>
    <div class="row">
        <span class="form-group col-md-6">
            <input type="text" id="nom" name="nom" placeholder="Votre nom *" class="required form-control" value="">
        </span>
        <span class="form-group col-md-6">
            <input type="text" id="prenom" name="prenom" placeholder="Votre prénom *" class="required form-control mb-0"
                value="">
    </div>
    <div class="row">
        <span class="form-group col-md-6">
            <input type="text" id="portable" name="portable" placeholder="Téléphone Portable *" class="required number form-control"
                minlength="10" maxlength="10" value="">
        </span>

        <span class="form-group col-md-6">
            <div class="input-group">
                <input type="text" id="telephone" name="telephone" placeholder="Téléphone secondaire" class="form-control number"
                    minlength="10" maxlength="10" value="">
            </div>
        </span>


        <div class="col-md-12">
            <div class="checkbox form-check-inline">
                <input type="checkbox" name="cgv" id="cgv" value="option1">
                <label for="cgv"> En cochant cette case vous validez les <a href="/cgv" target="_blank">CGV</a>
                concernant votre réservation </label>
            </div>
        </div>

    </div>

</div>
